title: FluxToolkit Guides
description: Master SEO, web development, and content writing with the official FluxToolkit guides. Learn to format JSON, optimize meta tags, and hit exact word counts.
url: "https://fluxtoolkit.github.io"
baseurl: "/fluxtoolkit-guides"
theme: minima
permalink: /:title/
future: true
google_site_verification: "GHzVG0AWlCbFLMUllhO1rf57oThTu6cDxa9qbZAGLxs"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
