title: FluxToolkit Guides
description: Official guides, tutorials, and listicles for developers, writers, and SEO experts using the free tools at FluxToolkit.com.
url: "https://fluxtoolkit.github.io"
baseurl: "/fluxtoolkit-guides"
theme: minima
permalink: /:title/
future: true
google_site_verification: "GHzVG0AWlCbFLMUllhO1rf57oThTu6cDxa9qbZAGLxs"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
